<?php
    $config['ignore_uri'] = array(
        'calendar/cities',
        'calendar/rail_cities',
        'calendar/bus_cities',
        'calendar/hotel_cities',
        'login',
        'login_page',
        'logout',
        'send_feedback',
        'send_sms',
        'remind_password',
        'my_main/user_info',
        'payment/response',
        'payment/result',
        'payment/balance',
        'avia/a/search',
        'avia/g/search',
        'cron/sendSMS',
        'social_nets',
        'cron/sendEmails',
        'timeout_save',
        'cron/get_sms_queue',
        'captcha/kcaptcha',
        'verify_email',
        'cron/get_email_queue',
        'cron/get_email_rating_airline'
    );
?>
